---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fluxcd.inishev.dev
  resources:
  - tankas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.inishev.dev
  resources:
  - tankas/finalizers
  verbs:
  - update
- apiGroups:
  - fluxcd.inishev.dev
  resources:
  - tankas/status
  verbs:
  - get
  - patch
  - update
