# permissions for end users to edit tankas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tanka-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tanka-controller-2
    app.kubernetes.io/part-of: tanka-controller-2
    app.kubernetes.io/managed-by: kustomize
  name: tanka-editor-role
rules:
- apiGroups:
  - fluxcd.inishev.dev
  resources:
  - tankas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.inishev.dev
  resources:
  - tankas/status
  verbs:
  - get
