namePrefix: tanka-
namespace: flux-system
resources:
- manager.yaml
images:
- name: controller
  newName: 656026053728.dkr.ecr.eu-central-1.amazonaws.com/tanka-controller
  newTag: master-e8636112-1697666668

